import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  {
    label: 'Home',
    route: '/'
  }, {
    label: 'Agregar capitulos a una temporada',
    route: '/addChapter'
  }, {
    label: 'Listar capitulos de una temporada',
    route: '/listChapters'
  },
  {
    label: 'Reservar un capitulo',
    route: '/reserveChapter'
  },
  {
    label: 'Pagar la reserva',
    route: '/paymentChapter'
  },
  {
    label: 'Listar capitulos reservados',
    route: '/listChapterReserved'
  },
  {
    label: 'Listar capitulos rentados',
    route: '/listChapterRented'
  }
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              {links?.map(({ label, route }) => (
                <li key={route}>
                  <Link href={route}>
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

        </header>
        <div id="container">
          {children}
        </div>
      </body>
    </html>
  );
}

